package com.example.shortener.link.web;

import com.example.shortener.common.error.ApiException;
import com.example.shortener.common.error.ErrorCode;
import com.example.shortener.config.OpenApiConfig;
import com.example.shortener.config.ShortenerProperties;
import com.example.shortener.link.CreateLinkCommand;
import com.example.shortener.link.Link;
import com.example.shortener.link.LinkService;
import com.example.shortener.link.LinkStatus;
import com.example.shortener.security.ApiKeyInterceptor;
import com.example.shortener.security.ApiScopes;
import com.example.shortener.security.RequiresApiKey;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import jakarta.validation.Valid;
import jakarta.validation.constraints.Pattern;
import java.net.URI;
import java.time.Clock;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestAttribute;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

/// Link management API. Thin by design: HTTP mapping only; rules live in [LinkService].
@RestController
@RequestMapping("/api/v1/links")
public class LinkController {

    private final LinkService links;
    private final Clock clock;
    private final String baseUrl;

    public LinkController(LinkService links, Clock clock, ShortenerProperties props) {
        this.links = links;
        this.clock = clock;
        this.baseUrl = props.baseUrl();
    }

    @Operation(summary = "Create a short link")
    @ApiResponse(responseCode = "201", description = "Created; Location header points to the new link")
    @ApiResponse(responseCode = "200", description = "Replay of an earlier request with the same Idempotency-Key")
    @ApiResponse(responseCode = "400", description = "Invalid URL, expiry or Idempotency-Key")
    @ApiResponse(responseCode = "401", description = "Missing, invalid or expired X-API-Key")
    @ApiResponse(responseCode = "403", description = "Key lacks the links:create scope")
    @ApiResponse(responseCode = "409", description = "Idempotency-Key reused with a different body")
    @ApiResponse(responseCode = "410", description = "Idempotency-Key replay, but that link was deleted or has expired")
    @ApiResponse(responseCode = "429", description = "Rate limited (per API key); see Retry-After")
    @SecurityRequirement(name = OpenApiConfig.API_KEY_SCHEME)
    @PostMapping
    @RequiresApiKey(scope = ApiScopes.LINKS_CREATE)
    public ResponseEntity<LinkResponse> create(
            @Valid @RequestBody CreateLinkRequest body,
            @Parameter(
                            description =
                                    "Optional. Generate a fresh UUID per new link (e.g. with uuidgen) and resend the"
                                            + " same value only when retrying after a timeout; the original link is returned"
                                            + " instead of a duplicate. Generated by the client, never by the server; scoped"
                                            + " to your API key.",
                            example = "3f6c2a9e-8b1d-4c7a-9e2f-5a1b7d0c4e88")
                    @RequestHeader(name = "Idempotency-Key", required = false)
                    String idempotencyKey,
            @RequestAttribute(ApiKeyInterceptor.CLIENT_ATTRIBUTE) String apiClient) {
        var result = links.create(new CreateLinkCommand(body.url(), body.expiresAt(), idempotencyKey, apiClient));
        LinkResponse response = LinkResponse.from(result.link(), baseUrl, clock.instant());
        if (result.replayed()) {
            return ResponseEntity.ok().header("Idempotent-Replayed", "true").body(response);
        }
        URI location = ServletUriComponentsBuilder.fromCurrentRequestUri()
                .path("/{code}")
                .buildAndExpand(response.code())
                .toUri();
        return ResponseEntity.created(location).body(response);
    }

    @Operation(summary = "Get link metadata")
    @ApiResponse(responseCode = "200", description = "Found (status may be EXPIRED)")
    @ApiResponse(responseCode = "400", description = "Malformed code")
    @ApiResponse(responseCode = "404", description = "Unknown code")
    @ApiResponse(responseCode = "410", description = "Deleted")
    @GetMapping("/{code}")
    public LinkResponse get(@PathVariable @Pattern(regexp = Link.CODE_PATTERN) String code) {
        Link link = links.get(code);
        if (link.status() == LinkStatus.DELETED) {
            throw new ApiException(ErrorCode.LINK_GONE, "Link '" + code + "' has been deleted");
        }
        return LinkResponse.from(link, baseUrl, clock.instant());
    }

    @Operation(summary = "Soft-delete a link; the code is never reused")
    @ApiResponse(responseCode = "204", description = "Deleted (also when already deleted)")
    @ApiResponse(responseCode = "401", description = "Missing, invalid or expired X-API-Key")
    @ApiResponse(responseCode = "403", description = "Key lacks the links:delete scope")
    @ApiResponse(responseCode = "404", description = "Unknown code")
    @SecurityRequirement(name = OpenApiConfig.API_KEY_SCHEME)
    @DeleteMapping("/{code}")
    @RequiresApiKey(scope = ApiScopes.LINKS_DELETE)
    public ResponseEntity<Void> delete(
            @PathVariable @Pattern(regexp = Link.CODE_PATTERN) String code,
            @RequestAttribute(ApiKeyInterceptor.CLIENT_ATTRIBUTE) String apiClient) {
        links.delete(code, apiClient);
        return ResponseEntity.noContent().build();
    }
}
