#!/usr/bin/env sh
# Generates a random API key and the SHA-256 hash the server is configured with.
#   - The KEY goes to the client (once, over a secure channel). The server never stores it.
#   - The HASH (plus name and scopes) is the server configuration.
#
# Usage:
#   scripts/new-api-key.sh <client-name> [--local] [--scopes links:create,links:delete,stats:read]
#     --local   also write the git-ignored files used for local runs:
#               config/application-local.yml (IntelliJ, bootRun) and .env (docker compose)
set -eu

name="${1:?usage: $0 <client-name> [--local] [--scopes links:create,links:delete,stats:read]}"
shift
local_files=false
scopes="links:create,links:delete,stats:read"
while [ $# -gt 0 ]; do
  case "$1" in
    --local) local_files=true ;;
    --scopes) scopes="${2:?--scopes needs a value}"; shift ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
  shift
done

key="$(openssl rand -base64 48 | LC_ALL=C tr -dc 'A-Za-z0-9' | cut -c1-40)"
hash="$(printf %s "$key" | (sha256sum 2>/dev/null || shasum -a 256) | cut -d' ' -f1)"

if [ "$local_files" = true ]; then
  mkdir -p config
  yaml_scopes="$(printf %s "$scopes" | sed 's/,/, /g')"
  cat > config/application-local.yml <<YAML
# Generated by scripts/new-api-key.sh. Git-ignored: NEVER commit. Loaded in the "local" profile (IntelliJ, bootRun).
shortener:
  api-keys:
    - name: $name
      sha256: $hash
      scopes: [$yaml_scopes]
YAML
  cat > .env <<DOTENV
# Generated by scripts/new-api-key.sh. Git-ignored: NEVER commit. Used by docker compose.
SHORTENER_APIKEYS_0_NAME=$name
SHORTENER_APIKEYS_0_SHA256=$hash
SHORTENER_APIKEYS_0_SCOPES=$scopes
DOTENV
  echo "Wrote config/application-local.yml and .env (both git-ignored)."
fi

echo
echo "Client : $name"
echo "Scopes : $scopes"
echo "API key: $key"
echo "         ^ give this to the client and use it as the X-API-Key header. It is shown only once."
echo "Server : SHORTENER_APIKEYS_0_NAME=$name SHORTENER_APIKEYS_0_SHA256=$hash SHORTENER_APIKEYS_0_SCOPES=$scopes"
